apiVersion: v2
dependencies:
  - name: kiali-operator
    repository: https://kiali.org/helm-charts
    version: "2.6.0"
description: |
  This chart installs kiali-operator
name: kiali-operator
version: "0"
