{{- if and .Values.gateway_config .Values.gateway_config.domain (ne .Values.gateway_config.domain "") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
spec:
  secretName: istio-gateway-tls
  issuerRef:
    name: {{ .Values.gateway_config.cluster_issuer | default "selfsigned-issuer" }}
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.gateway_config.domain }}"
{{- end }}
