{{- if .Values.gateway_config }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway_config.name | default "istio-gateway" }}
  {{- if and .Values.gateway_config.domain .Values.gateway_config.cluster_issuer (ne .Values.gateway_config.domain "") }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway_config.cluster_issuer }}
  {{- end }}
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      {{- if and .Values.gateway_config.domain (ne .Values.gateway_config.domain "") (ne .Values.gateway_config.domain "*") }}
      hostname: "*.{{ .Values.gateway_config.domain }}"
      {{- end }}
      allowedRoutes:
        namespaces:
          from: All
    {{- if and .Values.gateway_config.domain (ne .Values.gateway_config.domain "") (ne .Values.gateway_config.domain "*") }}
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.{{ .Values.gateway_config.domain }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: istio-gateway-tls
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
{{- end }}
