apiVersion: v2
dependencies:
  - name: ztunnel
    repository: https://istio-release.storage.googleapis.com/charts
    version: "*.*.*"
description: |
  This chart installs istio ztunnel
name: istio-ztunnel
version: "0"
